; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; vim:ts=2:sw=2:et:

#define MyAppName "WezTerm"
;#define MyAppVersion "1.5"
#define MyAppPublisher "Wez Furlong"
#define MyAppURL "http://wezterm.org"
#define MyAppExeName "wezterm-gui.exe"

; Directories holding the built binaries for each architecture.  Both are
; optional: whichever ones exist at compile time are included, so a single
; architecture build still produces a working installer.  ci/deploy.sh passes
; these explicitly.
#ifndef X64Dir
  #define X64Dir "..\target\release"
#endif
#ifndef Arm64Dir
  #define Arm64Dir "..\target\aarch64-pc-windows-msvc\release"
#endif

[Setup]
AppId={{BCF6F0DA-5B9A-408D-8562-F680AE6E1EAF}
ArchitecturesAllowed=x64compatible arm64
ArchitecturesInstallIn64BitMode=x64compatible arm64
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
;LicenseFile=..\LICENSE.md
; Remove the following line to run in administrative install mode (install for all users.)
;PrivilegesRequired=lowest
;PrivilegesRequiredOverridesAllowed=dialog
OutputDir=..
OutputBaseFilename=WezTerm-Setup
SetupIconFile=..\assets\windows\terminal.ico
UninstallDisplayIcon={app}\{#MyAppExeName}
Compression=lzma
SolidCompression=yes
WizardStyle=modern
; Build 1809 is required for pty support
MinVersion=10.0.17763
ChangesEnvironment=true

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

; Work out which architectures we have binaries for.  When both are present we
; emit a per-file Check so that each machine installs its native build; when
; only one is present those files install unconditionally, which preserves the
; existing behaviour of an x64-only installer running under emulation on arm64.
#define HaveX64 FileExists(AddBackslash(SourcePath) + X64Dir + "\wezterm.exe")
#define HaveArm64 FileExists(AddBackslash(SourcePath) + Arm64Dir + "\wezterm.exe")
#if !HaveX64 && !HaveArm64
  #error No built binaries found. Build wezterm first, or pass -DX64Dir / -DArm64Dir.
#endif
#if HaveX64 && HaveArm64
  #define X64Check "; Check: not IsArm64Target"
  #define Arm64Check "; Check: IsArm64Target"
#else
  #define X64Check ""
  #define Arm64Check ""
#endif

[Files]
#if HaveX64
Source: "{#X64Dir}\wezterm.exe"; DestDir: "{app}"; Flags: ignoreversion{#X64Check}
Source: "{#X64Dir}\wezterm-gui.exe"; DestDir: "{app}"; Flags: ignoreversion{#X64Check}
Source: "{#X64Dir}\wezterm-mux-server.exe"; DestDir: "{app}"; Flags: ignoreversion{#X64Check}
Source: "{#X64Dir}\strip-ansi-escapes.exe"; DestDir: "{app}"; Flags: ignoreversion{#X64Check}
Source: "{#X64Dir}\mesa\opengl32.dll"; DestDir: "{app}\mesa"; Flags: ignoreversion skipifsourcedoesntexist{#X64Check}
Source: "{#X64Dir}\libEGL.dll"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist{#X64Check}
Source: "{#X64Dir}\libGLESv2.dll"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist{#X64Check}
Source: "{#X64Dir}\conpty.dll"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist{#X64Check}
Source: "{#X64Dir}\OpenConsole.exe"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist{#X64Check}
#endif
#if HaveArm64
Source: "{#Arm64Dir}\wezterm.exe"; DestDir: "{app}"; Flags: ignoreversion{#Arm64Check}
Source: "{#Arm64Dir}\wezterm-gui.exe"; DestDir: "{app}"; Flags: ignoreversion{#Arm64Check}
Source: "{#Arm64Dir}\wezterm-mux-server.exe"; DestDir: "{app}"; Flags: ignoreversion{#Arm64Check}
Source: "{#Arm64Dir}\strip-ansi-escapes.exe"; DestDir: "{app}"; Flags: ignoreversion{#Arm64Check}
; mesa has no arm64 build; wezterm falls back to the system GL driver there
Source: "{#Arm64Dir}\mesa\opengl32.dll"; DestDir: "{app}\mesa"; Flags: ignoreversion skipifsourcedoesntexist{#Arm64Check}
Source: "{#Arm64Dir}\libEGL.dll"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist{#Arm64Check}
Source: "{#Arm64Dir}\libGLESv2.dll"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist{#Arm64Check}
Source: "{#Arm64Dir}\conpty.dll"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist{#Arm64Check}
Source: "{#Arm64Dir}\OpenConsole.exe"; DestDir: "{app}"; Flags: ignoreversion skipifsourcedoesntexist{#Arm64Check}
#endif
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; AppUserModelID: "org.wezfurlong.wezterm"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; AppUserModelID: "org.wezfurlong.wezterm"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Registry]
Root: HKA; Subkey: "Software\Classes\Drive\shell\Open WezTerm here"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\Drive\shell\Open WezTerm here"; ValueName: "icon"; ValueType: string; ValueData: "{app}\{#MyAppExeName}"; Flags: uninsdeletekey;
Root: HKA; Subkey: "Software\Classes\Drive\shell\Open WezTerm here\command"; ValueType: string; ValueData: """{app}\{#MyAppExeName}"" start --no-auto-connect --cwd ""%V\"""; Flags: uninsdeletekey;
Root: HKA; Subkey: "Software\Classes\Directory\Background\shell\Open WezTerm here"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\Directory\Background\shell\Open WezTerm here"; ValueName: "icon"; ValueType: string; ValueData: "{app}\{#MyAppExeName}"; Flags: uninsdeletekey;
Root: HKA; Subkey: "Software\Classes\Directory\Background\shell\Open WezTerm here\command"; ValueType: string; ValueData: """{app}\{#MyAppExeName}"" start --no-auto-connect --cwd ""%V"; Flags: uninsdeletekey;
Root: HKA; Subkey: "Software\Classes\Directory\shell\Open WezTerm here"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\Directory\shell\Open WezTerm here"; ValueName: "icon"; ValueType: string; ValueData: "{app}\{#MyAppExeName}"; Flags: uninsdeletekey;
Root: HKA; Subkey: "Software\Classes\Directory\shell\Open WezTerm here\command"; ValueType: string; ValueData: """{app}\{#MyAppExeName}"" start --no-auto-connect --cwd ""%V\\"""; Flags: uninsdeletekey;

[Code]
{ https://stackoverflow.com/a/46609047/149111 }
const EnvironmentKey = 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment';

const IMAGE_FILE_MACHINE_AMD64 = $8664;

{ True when the machine we are installing on is arm64.  Used to pick the
  native binaries when the installer carries both architectures. }
function IsArm64Target(): Boolean;
begin
  Result := ProcessorArchitecture = paArm64;
end;

function GetMachineTypeAttributes(
    Machine: Word; var MachineTypeAttributes: Integer): HRESULT;
  external 'GetMachineTypeAttributes@Kernel32.dll stdcall delayload';

function IsSupportedArch(): Boolean;
var
  Version: TWindowsVersion;
  MachineTypeAttributes: Integer;
  Arch: TSetupProcessorArchitecture;
begin
  GetWindowsVersionEx(Version);
  // Use capability detection if available. GetMachineTypeAttributes is
  // available starting Build 22000
  if Version.Build >= 22000 then
  begin
    OleCheck(
      GetMachineTypeAttributes(IMAGE_FILE_MACHINE_AMD64, MachineTypeAttributes)
    );
    Result := MachineTypeAttributes <> 0;
  end
  else
  begin
    // If capability detection is not available, then we rely on build number.
    // x64 emulation on arm64 is available starting build 21277 so both x64 and
    // arm64 will work
    if Version.Build >= 21277 then
    begin
      Result := True;
    end
    else
    begin
      // If we're here, it means we're on a build between 17763 and 21277
      // because Inno will check MinVersion 10.0.17763 and arch will be x64 or
      // arm64. Only x64 is supported in this build range
      Arch := ProcessorArchitecture;
      Result := Arch = paX64;
    end
  end;
end;

<event('InitializeSetup')>
function InitializeSetupCheckArchitecture(): Boolean;
begin
  Result := IsSupportedArch();
end;

procedure EnvAddPath(instlPath: string);
var
  Paths: string;
begin
  { Retrieve current path (use empty string if entry not exists) }
  if not RegQueryStringValue(HKEY_LOCAL_MACHINE, EnvironmentKey, 'Path', Paths) then
    Paths := '';

  if Paths = '' then
    Paths := instlPath + ';'
  else
  begin
    { Skip if string already found in path }
    if Pos(';' + Uppercase(instlPath) + ';',  ';' + Uppercase(Paths) + ';') > 0 then exit;
    if Pos(';' + Uppercase(instlPath) + '\;', ';' + Uppercase(Paths) + ';') > 0 then exit;

    { Append App Install Path to the end of the path variable }
    if Paths[length(Paths)] <> ';' then
      Paths := Paths + ';';

    Paths := Paths + instlPath + ';';
  end;

  { Overwrite (or create if missing) path environment variable }
  if RegWriteStringValue(HKEY_LOCAL_MACHINE, EnvironmentKey, 'Path', Paths)
  then Log(Format('The [%s] added to PATH: [%s]', [instlPath, Paths]))
  else Log(Format('Error while adding the [%s] to PATH: [%s]', [instlPath, Paths]));
end;

procedure EnvRemovePath(instlPath: string);
var
  Paths: string;
  P, Offset, DelimLen: Integer;
begin
  { Skip if registry entry not exists }
  if not RegQueryStringValue(HKEY_LOCAL_MACHINE, EnvironmentKey, 'Path', Paths) then
    exit;

  { Skip if string not found in path }
  DelimLen := 1;     { Length(';') }
  P := Pos(';' + Uppercase(instlPath) + ';', ';' + Uppercase(Paths) + ';');
  if P = 0 then
  begin
    { perhaps instlPath lives in Paths, but terminated by '\;' }
    DelimLen := 2; { Length('\;') }
    P := Pos(';' + Uppercase(instlPath) + '\;', ';' + Uppercase(Paths) + ';');
    if P = 0 then exit;
  end;

  { Decide where to start string subset in Delete() operation. }
  if P = 1 then
    Offset := 0
  else
    Offset := 1;
  { Update path variable }
  Delete(Paths, P - Offset, Length(instlPath) + DelimLen);

  { Overwrite path environment variable }
  if RegWriteStringValue(HKEY_LOCAL_MACHINE, EnvironmentKey, 'Path', Paths)
  then Log(Format('The [%s] removed from PATH: [%s]', [instlPath, Paths]))
  else Log(Format('Error while removing the [%s] from PATH: [%s]', [instlPath, Paths]));
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
    EnvAddPath(ExpandConstant('{app}'));
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep = usPostUninstall then
    EnvRemovePath(ExpandConstant('{app}'));
end;
